export { listRoutes } from './list'
export { typesRoutes } from './types'
export { searchRoutes } from './search'
export { detailRoutes } from './detail'
export { hotRoutes } from './hot'
export { sourcesRoutes } from './sources'